// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfzmnkpepfrubjpifnna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mem1ua3BlcGZydWJqcGlmbm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzQ1MDgsImV4cCI6MjA2NzY1MDUwOH0.OIpe_wiOM-ypU65Q0qAmk1Xd0Hilm-oR1VeJbHTdzt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});